services:
  coredns:
    image: coredns/coredns
    container_name: coredns
    restart: always
    volumes:
      - ./Corefile:/tmp/Corefile
      - ./example.db:/tmp/example.db
    ports:
      - "53:53/udp"
    command: -conf /tmp/Corefile
