services:
  coredns:
    image: coredns/coredns
    container_name: coredns
    restart: always
    volumes:
      - ./Corefile:/coredns/Corefile
      - ./example.db:/coredns/example.db
    ports:
      - "53:53/udp"
    command: -conf /coredns/Corefile
