services:
  coredns:
    image: coredns/coredns
    container_name: coredns
    restart: always
    volumes:
      - ./Corefile:/etc/Corefile
      - ./example.db:/etc/example.db
    ports:
      - "53:53/udp"
    command: -conf /etc/Corefile
